# Generated by Django 5.2.16 on 2026-08-31 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Номер')),
                ('first_name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('delivery_service', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('courier', 'Курʼєр'), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Доставка')),
                ('delivery_city', models.CharField(max_length=150, verbose_name='Місто')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адреса / відділення')),
                ('payment_method', models.CharField(choices=[('online', 'Онлайн оплата'), ('cod', 'Оплата при отриманні'), ('bank_transfer', 'Безготівковий розрахунок')], default='cod', max_length=20, verbose_name='Оплата')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума товарів')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Знижка')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доставка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Разом')),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('market', models.CharField(default='UA', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Нове'), ('awaiting_payment', 'Очікує оплату'), ('paid', 'Оплачено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('variant_name', models.CharField(blank=True, max_length=120)),
                ('product_sku', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Позиція',
                'verbose_name_plural': 'Позиції',
            },
        ),
    ]
