# Generated by Django 5.2.16 on 2026-09-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП CityRef'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_ttn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ТТН'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_ttn_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП TTN Ref'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП WarehouseRef'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay')], default='liqpay', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Створено'), ('pending', 'В очікуванні'), ('success', 'Успішно'), ('failure', 'Помилка'), ('reversed', 'Повернено')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('liqpay_order_id', models.CharField(max_length=64, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
