# Generated by Django 5.2.16

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_np_city_ref_order_np_ttn_order_np_ttn_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fx_rate',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('1'),
                help_text='Гривень за 1 одиницю валюти замовлення на момент оформлення.',
                max_digits=12,
                verbose_name='Курс до UAH',
            ),
        ),
    ]
