# Generated by Django 5.2.16 on 2026-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП CityRef'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП WarehouseRef'),
        ),
    ]
