# Generated by Django 5.2.16 on 2026-08-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(choices=[('strength', 'Міцність'), ('format', 'Формат'), ('country', 'Країна'), ('budget', 'Бюджет')], max_length=32, unique=True, verbose_name='Крок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Підказка')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Крок калькулятора',
                'verbose_name_plural': 'Кроки калькулятора',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Варіант')),
                ('value', models.CharField(max_length=64, verbose_name='Значення')),
                ('filter_field', models.CharField(help_text='напр. strength / country / shape / budget_max', max_length=64, verbose_name='Поле фільтра')),
                ('filter_value', models.CharField(max_length=64, verbose_name='Значення фільтра')),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='Пояснення')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calculator.calculatorquestion')),
            ],
            options={
                'verbose_name': 'Варіант відповіді',
                'verbose_name_plural': 'Варіанти відповідей',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
