# Generated by Django 5.2.16 on 2026-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatoroption',
            name='explanation_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пояснення'),
        ),
        migrations.AddField(
            model_name='calculatoroption',
            name='explanation_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пояснення'),
        ),
        migrations.AddField(
            model_name='calculatoroption',
            name='explanation_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пояснення'),
        ),
        migrations.AddField(
            model_name='calculatoroption',
            name='label_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Варіант'),
        ),
        migrations.AddField(
            model_name='calculatoroption',
            name='label_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Варіант'),
        ),
        migrations.AddField(
            model_name='calculatoroption',
            name='label_zh_hans',
            field=models.CharField(max_length=120, null=True, verbose_name='Варіант'),
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='help_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підказка'),
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='help_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підказка'),
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='help_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підказка'),
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='calculatorquestion',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
