# Generated by Django 5.2.16 on 2026-09-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product_variant',
        ),
    ]
