# Generated by Django 5.2.16 on 2026-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_uniq_cart_product_variant'),
        ('catalog', '0010_productimage_ua_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_product'),
        ),
    ]
