# Generated by Django 5.2.16 on 2026-09-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Заповнюється автоматично. Можна залишити порожнім.', max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=160, verbose_name='Назва')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='Коротка назва')),
                ('mono', models.CharField(blank=True, max_length=8, verbose_name='Монограма')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Країна')),
                ('panel', models.CharField(choices=[('amber', 'Amber'), ('burgundy', 'Burgundy'), ('green', 'Green'), ('brown', 'Brown')], default='amber', max_length=16, verbose_name='Колір панелі')),
                ('cover', models.ImageField(blank=True, upload_to='mobile/brands/', verbose_name='Обкладинка')),
                ('heritage', models.TextField(blank=True, verbose_name='Історія / heritage')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бренд гайду',
                'verbose_name_plural': 'Бренди гайду',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MobileLegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('privacy', 'Політика конфіденційності'), ('terms', 'Умови'), ('age', 'Вікова політика'), ('about', 'Про застосунок')], max_length=32, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Юридична сторінка',
                'verbose_name_plural': 'Юридичні сторінки',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MobileScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('splash', 'Splash'), ('age', 'Вікова перевірка'), ('home', 'Головна'), ('house', 'Дім'), ('visit', 'Візит')], max_length=32, unique=True, verbose_name='Екран')),
                ('kicker', models.CharField(blank=True, max_length=120, verbose_name='Kicker')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_secondary', models.TextField(blank=True, verbose_name='Текст (дод.)')),
                ('cta_primary', models.CharField(blank=True, max_length=120, verbose_name='CTA основна')),
                ('cta_secondary', models.CharField(blank=True, max_length=120, verbose_name='CTA друга')),
                ('confirm_label', models.CharField(blank=True, max_length=120, verbose_name='Кнопка підтвердження')),
                ('legal_note', models.TextField(blank=True, verbose_name='Юридична примітка')),
                ('success_title', models.CharField(blank=True, max_length=255, verbose_name='Успіх: заголовок')),
                ('success_body', models.TextField(blank=True, verbose_name='Успіх: текст')),
                ('hero_image', models.ImageField(blank=True, upload_to='mobile/screens/', verbose_name='Hero / фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Екран застосунку',
                'verbose_name_plural': 'Екрани застосунку',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MobileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(default='Royal Smoke · v1.0', max_length=64, verbose_name='Версія в UI')),
                ('app_blurb', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('contact_address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('contact_phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('contact_hours', models.CharField(blank=True, max_length=255, verbose_name='Години роботи')),
                ('contact_lat', models.FloatField(default=50.4501, verbose_name='Широта')),
                ('contact_lng', models.FloatField(default=30.5226, verbose_name='Довгота')),
                ('app_seal', models.ImageField(blank=True, help_text='Іконка/печатка всередині апки (splash, Ще). Не змінює App Icon у Store.', upload_to='mobile/seal/', verbose_name='Печатка в застосунку')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування застосунку',
                'verbose_name_plural': 'Налаштування застосунку',
            },
        ),
        migrations.CreateModel(
            name='MobileBrandFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Мітка')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='mobile.mobilebrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Факт бренду',
                'verbose_name_plural': 'Факти бренду',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MobileBrandLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Назва лінії')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mobile.mobilebrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Лінія бренду',
                'verbose_name_plural': 'Лінії бренду',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MobileBrandPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile/brands/photos/', verbose_name='Фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mobile.mobilebrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Фото бренду',
                'verbose_name_plural': 'Фото брендів',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MobileHouseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_label', models.CharField(default='01', max_length=8, verbose_name='Індекс')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('screen', models.ForeignKey(limit_choices_to={'key': 'house'}, on_delete=django.db.models.deletion.CASCADE, related_name='house_blocks', to='mobile.mobilescreen', verbose_name='Екран')),
            ],
            options={
                'verbose_name': 'Блок «Дім»',
                'verbose_name_plural': 'Блоки «Дім»',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
