# Generated by Django 5.2.16 on 2026-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Фото')),
                ('cta_primary_label', models.CharField(blank=True, default='До каталогу', max_length=80, verbose_name='CTA primary')),
                ('cta_primary_url', models.CharField(blank=True, default='/catalog/', max_length=255, verbose_name='CTA primary URL')),
                ('cta_secondary_label', models.CharField(blank=True, default='Сигари', max_length=80, verbose_name='CTA secondary')),
                ('cta_secondary_url', models.CharField(blank=True, default='/catalog/cigars/', max_length=255, verbose_name='CTA secondary URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Слайд hero',
                'verbose_name_plural': 'Слайди hero',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Royal Smoke', max_length=100, verbose_name='Назва сайту')),
                ('phone', models.CharField(blank=True, default='+380 44 000 00 00', max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='hello@royalsmoke.ua', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='Київ, Україна', max_length=255, verbose_name='Адреса')),
                ('work_hours', models.CharField(blank=True, default='Пн–Нд: 11:00–21:00', max_length=255, verbose_name='Години роботи')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('notify_emails', models.TextField(blank=True, help_text='Адреси через кому або з нового рядка.', verbose_name='Email для сповіщень')),
                ('telegram_notify_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram канал/чат для лідів')),
                ('free_delivery_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Безкоштовна доставка від')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description головної')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('catalog', 'Каталог'), ('service', 'Сервіс')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ блоку')),
                ('label', models.CharField(max_length=128, verbose_name='Назва в адмінці')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото')], default='text', max_length=16)),
                ('text_html', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_rs_site_block_page_key')],
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Про нас',
                'verbose_name_plural': 'Головна — Про нас',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCategoriesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Категорії',
                'verbose_name_plural': 'Головна — Категорії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeNewSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Новинки',
                'verbose_name_plural': 'Головна — Новинки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeServiceSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Сервіс',
                'verbose_name_plural': 'Головна — Сервіс',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeTopSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Топ продажів',
                'verbose_name_plural': 'Головна — Топ продажів',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Меню / Header',
                'verbose_name_plural': 'Меню / Header',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
    ]
