# Generated by Django 5.2.16 on 2026-09-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historyslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaboutsettings',
            options={'verbose_name': 'Головна — Історія сигар', 'verbose_name_plural': 'Головна — Історія сигар'},
        ),
        migrations.AddField(
            model_name='historyslide',
            name='image',
            field=models.ImageField(blank=True, upload_to='history/', verbose_name='Фото'),
        ),
    ]
