# Generated by Django 5.2.16 on 2026-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historyslide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='cta_primary_label_en',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='CTA primary'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_primary_label_uk',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='CTA primary'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_primary_label_zh_hans',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='CTA primary'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_secondary_label_en',
            field=models.CharField(blank=True, default='Сигари', max_length=80, null=True, verbose_name='CTA secondary'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_secondary_label_uk',
            field=models.CharField(blank=True, default='Сигари', max_length=80, null=True, verbose_name='CTA secondary'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_secondary_label_zh_hans',
            field=models.CharField(blank=True, default='Сигари', max_length=80, null=True, verbose_name='CTA secondary'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='cta_label_en',
            field=models.CharField(blank=True, default='Читати далі', max_length=80, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='cta_label_uk',
            field=models.CharField(blank=True, default='Читати далі', max_length=80, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='cta_label_zh_hans',
            field=models.CharField(blank=True, default='Читати далі', max_length=80, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='text_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='year_label_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Рік / мітка'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='year_label_uk',
            field=models.CharField(max_length=40, null=True, verbose_name='Рік / мітка'),
        ),
        migrations.AddField(
            model_name='historyslide',
            name='year_label_zh_hans',
            field=models.CharField(max_length=40, null=True, verbose_name='Рік / мітка'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='text_html_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='text_html_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='text_html_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_zh_hans',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Royal Smoke', max_length=100, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uk',
            field=models.CharField(default='Royal Smoke', max_length=100, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_zh_hans',
            field=models.CharField(default='Royal Smoke', max_length=100, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_en',
            field=models.CharField(blank=True, default='Пн–Нд: 11:00–21:00', max_length=255, null=True, verbose_name='Години роботи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_uk',
            field=models.CharField(blank=True, default='Пн–Нд: 11:00–21:00', max_length=255, null=True, verbose_name='Години роботи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_zh_hans',
            field=models.CharField(blank=True, default='Пн–Нд: 11:00–21:00', max_length=255, null=True, verbose_name='Години роботи'),
        ),
    ]
