# Generated by Django 5.2.16 on 2026-09-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_country_i18n'),
        ('core', '0004_i18n_modeltranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrandCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home_brands/', verbose_name='Фото картки')),
                ('text', models.TextField(blank=True, verbose_name='Текст на картці')),
                ('text_uk', models.TextField(blank=True, null=True, verbose_name='Текст на картці')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст на картці')),
                ('text_zh_hans', models.TextField(blank=True, null=True, verbose_name='Текст на картці')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_cards', to='catalog.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Картка бренду на головній',
                'verbose_name_plural': 'Картки брендів на головній',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='HomeCategoriesSettings',
        ),
        migrations.DeleteModel(
            name='HomeNewSettings',
        ),
        migrations.DeleteModel(
            name='HomeTopSettings',
        ),
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='AgeGateSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Age gate',
                'verbose_name_plural': 'Age gate',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='B2bPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'B2B',
                'verbose_name_plural': 'B2B',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='BookingPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CabinetPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Кабінет',
                'verbose_name_plural': 'Кабінет',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CartPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошик',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CatalogPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог — тексти',
                'verbose_name_plural': 'Каталог — тексти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CheckoutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Оформлення',
                'verbose_name_plural': 'Оформлення',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='DeliveryPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='FaqPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ — шапка',
                'verbose_name_plural': 'FAQ — шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeBrandsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Бренди',
                'verbose_name_plural': 'Бренди',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCalculatorSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Калькулятор',
                'verbose_name_plural': 'Калькулятор',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCatalogSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог на головній',
                'verbose_name_plural': 'Каталог на головній',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterModelOptions(
            name='homeaboutsettings',
            options={'verbose_name': 'Історія сигар', 'verbose_name_plural': 'Історія сигар'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
        migrations.AlterModelOptions(
            name='homeservicesettings',
            options={'verbose_name': 'Сервіс', 'verbose_name_plural': 'Сервіс'},
        ),
        migrations.AlterModelOptions(
            name='siteheadersettings',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('catalog', 'Каталог'), ('service', 'Сервіс'), ('about', 'Про нас'), ('faq', 'FAQ'), ('contact', 'Контакти'), ('delivery', 'Доставка'), ('b2b', 'B2B'), ('booking', 'Бронювання'), ('cart', 'Кошик'), ('checkout', 'Оформлення'), ('cabinet', 'Кабінет'), ('age', 'Age gate')], max_length=32, verbose_name='Сторінка'),
        ),
    ]
