# Generated by Django 5.2.16 on 2026-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cms_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Блог — шапка',
                'verbose_name_plural': 'Блог — шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterModelOptions(
            name='agegatesettings',
            options={'verbose_name': 'Вікова перевірка', 'verbose_name_plural': 'Вікова перевірка'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Слайд банера', 'verbose_name_plural': 'Слайди банера'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Головний банер', 'verbose_name_plural': 'Головний банер'},
        ),
        migrations.AlterModelOptions(
            name='sitefootersettings',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='siteheadersettings',
            options={'verbose_name': 'Шапка', 'verbose_name_plural': 'Шапка'},
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_primary_label',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, verbose_name='Основна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_primary_label_en',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='Основна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_primary_label_uk',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='Основна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_primary_label_zh_hans',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='Основна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_primary_url',
            field=models.CharField(blank=True, default='/catalog/', max_length=255, verbose_name='URL основної кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_label',
            field=models.CharField(blank=True, default='Сигари', max_length=80, verbose_name='Другорядна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_label_en',
            field=models.CharField(blank=True, default='Сигари', max_length=80, null=True, verbose_name='Другорядна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_label_uk',
            field=models.CharField(blank=True, default='Сигари', max_length=80, null=True, verbose_name='Другорядна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_label_zh_hans',
            field=models.CharField(blank=True, default='Сигари', max_length=80, null=True, verbose_name='Другорядна кнопка'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_url',
            field=models.CharField(blank=True, default='/catalog/cigars/', max_length=255, verbose_name='URL другорядної кнопки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-опис головної'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис головної'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис головної'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис головної'),
        ),
    ]
