# Generated by Django 5.2.16 on 2026-09-23 08:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('catalog', 'Каталог'), ('service', 'Сервіс'), ('about', 'Про нас'), ('blog', 'Блог'), ('faq', 'FAQ'), ('contact', 'Контакти'), ('delivery', 'Доставка'), ('b2b', 'B2B'), ('booking', 'Бронювання'), ('cart', 'Кошик'), ('checkout', 'Оформлення'), ('cabinet', 'Кабінет'), ('age', 'Age gate')], max_length=32, unique=True, verbose_name='Сторінка')),
                ('background_color', models.CharField(blank=True, help_text='HEX (#100d0c). Порожнє значення — дефолтний стиль сайту.', max_length=32, verbose_name='Колір фону')),
            ],
            options={
                'verbose_name': 'Стиль сторінки',
                'verbose_name_plural': 'Стилі сторінок',
                'ordering': ['page'],
            },
        ),
        migrations.AddField(
            model_name='siteblock',
            name='link_label',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст посилання'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='link_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='URL посилання'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='video_embed_url',
            field=models.URLField(blank=True, verbose_name='URL відео (YouTube/Vimeo)'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='video_file',
            field=models.FileField(blank=True, upload_to='blocks/video/', verbose_name='Відеофайл'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='uah_per_unit',
            field=models.DecimalField(decimal_places=4, help_text='Скільки гривень коштує 1 одиниця цієї валюти. Для UAH завжди 1.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Гривень за 1 одиницю'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання'), ('video', 'Відео')], default='text', max_length=16),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('catalog', 'Каталог'), ('service', 'Сервіс'), ('about', 'Про нас'), ('blog', 'Блог'), ('faq', 'FAQ'), ('contact', 'Контакти'), ('delivery', 'Доставка'), ('b2b', 'B2B'), ('booking', 'Бронювання'), ('cart', 'Кошик'), ('checkout', 'Оформлення'), ('cabinet', 'Кабінет'), ('age', 'Age gate')], max_length=32, verbose_name='Сторінка'),
        ),
    ]
