# Generated by Django 5.2.16 on 2026-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cms_page_style_video_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('region', 'Доставка'), ('payment', 'Оплата')], db_index=True, max_length=16, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_uk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_zh_hans', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Картка доставки/оплати',
                'verbose_name_plural': 'Картки доставки/оплати',
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
    ]
