# Generated by Django 5.2.16 on 2026-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delivery_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Акцент (кнопки, золото). HEX. Порожнє — дефолт сайту.', max_length=32, verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='text_color',
            field=models.CharField(blank=True, help_text='HEX. Порожнє — дефолт сайту.', max_length=32, verbose_name='Колір шрифта'),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='background_color',
            field=models.CharField(blank=True, help_text='HEX. Порожнє — дефолт сайту.', max_length=32, verbose_name='Колір фону'),
        ),
    ]
