# Generated by Django 5.2.16 on 2026-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('callback', 'Зворотний дзвінок'), ('b2b', 'B2B запит'), ('chat', 'Чат'), ('newsletter', 'Підписка'), ('contact', 'Контактна форма')], max_length=32, verbose_name='Тип')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Імʼя')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Компанія')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані')),
                ('source_url', models.CharField(blank=True, max_length=255, verbose_name='Джерело')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лід',
                'verbose_name_plural': 'Ліди',
                'ordering': ['-created_at'],
            },
        ),
    ]
