# Generated by Django 5.2.16 on 2026-08-31 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tasting', 'Дегустація'), ('consultation', 'Консультація сомельє'), ('showroom', 'Візит у шоурум'), ('pickup', 'Самовивіз')], max_length=32, unique=True, verbose_name='Тип')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Тривалість, хв')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Місць на слот')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Послуга бронювання',
                'verbose_name_plural': 'Послуги бронювання',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Початок')),
                ('ends_at', models.DateTimeField(verbose_name='Кінець')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Місткість')),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.bookingservice')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоти',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('done', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.bookingslot')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['starts_at', 'is_active'], name='booking_boo_starts__af6f4f_idx'),
        ),
    ]
