# Generated by Django 5.2.16 on 2026-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_request_optional_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='title_en',
            field=models.CharField(max_length=160, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='title_uk',
            field=models.CharField(max_length=160, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='title_zh_hans',
            field=models.CharField(max_length=160, null=True, verbose_name='Назва'),
        ),
    ]
