# Generated by Django 5.2.16 on 2026-09-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('question_uk', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('question_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('answer_uk', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_en', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_zh_hans', models.TextField(null=True, verbose_name='Відповідь')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Питання FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_uk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_zh_hans', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Legal-документ',
                'verbose_name_plural': 'Legal-документи',
                'ordering': ['sort_order', 'slug'],
            },
        ),
    ]
