# Generated by Django 5.2.16 on 2026-09-22 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_cms_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('excerpt_uk', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('excerpt_en', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('excerpt_zh_hans', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('body', models.TextField(blank=True, verbose_name='Текст статті')),
                ('body_uk', models.TextField(blank=True, null=True, verbose_name='Текст статті')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст статті')),
                ('body_zh_hans', models.TextField(blank=True, null=True, verbose_name='Текст статті')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/', verbose_name='Обкладинка')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt обкладинки')),
                ('cover_alt_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt обкладинки')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt обкладинки')),
                ('cover_alt_zh_hans', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt обкладинки')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('meta_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок')),
                ('meta_title_zh_hans', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-опис')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='SEO-опис')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='SEO-опис')),
                ('meta_description_zh_hans', models.TextField(blank=True, null=True, verbose_name='SEO-опис')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Блог',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='pages_blogp_is_publ_db142e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('question_uk', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('question_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('answer_uk', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_en', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_zh_hans', models.TextField(null=True, verbose_name='Відповідь')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='pages.blogpost', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'FAQ статті',
                'verbose_name_plural': 'FAQ статей',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
