# Generated by Django 5.2.16 on 2026-09-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заповнюється автоматично з назви. Можна залишити порожнім.', max_length=280, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заповнюється автоматично з назви. Можна залишити порожнім.', max_length=64, unique=True, verbose_name='Slug'),
        ),
    ]
