from __future__ import annotations

from django.utils.translation import gettext_lazy as _

PAGE_DEFAULTS: dict[tuple[str, str], str] = {
    ('site', 'header_search_placeholder'): _('Пошук сигар, брендів, аксесуарів…'),
    ('site', 'nav_home'): _('Головна'),
    ('site', 'nav_catalog'): _('Каталог'),
    ('site', 'nav_sale'): _('Акції'),
    ('site', 'nav_faq'): _('FAQ'),
    ('site', 'nav_about'): _('Про нас'),
    ('site', 'nav_blog'): _('Блог'),
    ('site', 'nav_contact'): _('Контакти'),
    ('site', 'nav_delivery'): _('Доставка і оплата'),
    ('site', 'nav_callback'): _('Замовити дзвінок'),
    ('site', 'drawer_shop'): _('Покупка'),
    ('site', 'drawer_info'): _('Інфо'),
    ('site', 'footer_tagline'): _('Сигари, відібрані вручну для тих, хто знає різницю.'),
    ('site', 'footer_wordmark'): 'ROYAL SMOKE',
    ('site', 'footer_copyright'): _('© 2026 ROYAL SMOKE'),
    ('site', 'footer_seal'): '',
    ('site', 'footer_col_catalog'): _('Каталог'),
    ('site', 'footer_col_shop'): _('Покупка'),
    ('site', 'footer_col_info'): _('Інфо'),
    ('site', 'footer_link_cigars'): _('Сигари'),
    ('site', 'footer_link_accessories'): _('Аксесуари'),
    ('site', 'footer_link_brands'): _('Бренди'),
    ('site', 'footer_link_calculator'): _('Калькулятор'),
    ('site', 'footer_link_cart'): _('Кошик'),
    ('site', 'footer_link_cabinet'): _('Кабінет'),
    ('site', 'footer_link_privacy'): _('Приватність'),
    ('blog', 'kicker'): _('Гід і культура'),
    ('blog', 'title'): _('Блог'),
    ('blog', 'lead'): _(
        'Практичні гіди про сигари, зберігання, аксесуари та смак — '
        'від сомельє Royal Smoke.'
    ),
    ('blog', 'meta_description'): _(
        'Блог Royal Smoke: як обрати сигару, зберігати в хумідорі, '
        'підібрати аксесуари та читати вітолу. Поради експертів.'
    ),
    ('blog', 'read_more'): _('Читати'),
    ('blog', 'back'): _('Усі статті'),
    ('blog', 'related'): _('Читайте також'),
    ('about', 'kicker'): _('Про нас'),
    ('about', 'title'): _('Хроніка одного рішення'),
    ('about', 'lead'): _(
        'Royal Smoke — tobacco atelier, зібраний навколо простого правила: '
        'продавати лише те, що самі готові курити.'
    ),
    ('about', 'image'): '',
    ('about', 'years_num'): '7',
    ('about', 'years_label'): _('років на ринку'),
    ('about', 'era1_year'): '2019',
    ('about', 'era1_title'): _('Перший кабінет'),
    ('about', 'era1_text'): _(
        'Почали з невеликого простору в Києві: кілька полиць, ручний відбір '
        'і розмова з кожним гостем замість випадкової вітрини.'
    ),
    ('about', 'era2_year'): '2021',
    ('about', 'era2_title'): _('Прямі мануфактури'),
    ('about', 'era2_text'): _(
        'Налагодили прямі поставки з Нікарагуа, Домінікани та Куби — '
        'без зайвих посередників, з чесною ціною і стабільною якістю партій.'
    ),
    ('about', 'era3_year'): '2023',
    ('about', 'era3_title'): _('Власний хумідор'),
    ('about', 'era3_text'): _(
        'Збудували сховище зі стабільною вологістю й зібрали команду сомельє, '
        'яка супроводжує замовлення від першої консультації до доставки.'
    ),
    ('about', 'era4_year'): _('Сьогодні'),
    ('about', 'era4_title'): _('Бутік, каталог, сервіс'),
    ('about', 'era4_text'): _(
        'Працюємо як бутік і як точний онлайн-каталог: консультація, '
        'термобокс і доставка, яка береже лист.'
    ),
    ('faq', 'title'): 'FAQ',
    ('faq', 'lead'): _('Короткі відповіді про замовлення, зберігання та доставку.'),
    ('faq', 'bg'): '',
    ('contact', 'kicker'): _('Контакти'),
    ('contact', 'title'): _('Напишіть нам'),
    ('contact', 'lead'): _('Відповідаємо протягом робочого дня.'),
    ('contact', 'map_label'): _('Карта — Хрещатик 1'),
    ('contact', 'submit'): _('Надіслати'),
    ('contact', 'callback'): _('Замовити дзвінок'),
    ('delivery', 'title'): _('Доставка і оплата'),
    ('delivery', 'lead'): _('Київ — того ж дня · Україна — 1–2 дні · ЄС — 3–5 днів.'),
    ('delivery', 'bg'): '',
    ('delivery', 'h2'): _('Доставка'),
    ('delivery', 'pay_h2'): _('Оплата'),
    ('delivery', 'pay_intro'): _('Доступні способи оплати під час оформлення замовлення:'),
    ('b2b', 'title'): 'B2B',
    ('b2b', 'lead'): _('Прайс і умови для барів, готелів і корпоративних подарунків.'),
    ('b2b', 'submit'): _('Запросити прайс'),
    ('booking', 'title'): _('Бронювання'),
    ('booking', 'lead'): _('Оберіть послугу, дату та вільний слот.'),
    ('booking', 'submit'): _('Забронювати'),
    ('catalog', 'empty'): _('Каталог наповнюється.'),
    ('cart', 'title'): _('Кошик'),
    ('cart', 'empty'): _('Кошик порожній.'),
    ('cart', 'empty_cta'): _('До каталогу'),
    ('cart', 'continue'): _('Продовжити покупки'),
    ('cart', 'checkout'): _('Оформити замовлення'),
    ('cart', 'remove'): _('Видалити'),
    ('checkout', 'title'): _('Оформлення'),
    ('checkout', 'lead'): _('Заповніть контакти та спосіб доставки.'),
    ('checkout', 'submit'): _('Підтвердити замовлення'),
    ('checkout', 'summary'): _('Ваше замовлення'),
    ('checkout', 'age'): _('Підтверджую, що мені є 21 рік'),
    ('cabinet', 'title'): _('Кабінет'),
    ('cabinet', 'lead'): _('Вітаємо, {name}'),
    ('cabinet', 'profile'): _('Профіль'),
    ('cabinet', 'orders'): _('Замовлення'),
    ('cabinet', 'empty'): _('Замовлень ще немає'),
    ('cabinet', 'quick'): _('Швидкі дії'),
    ('age', 'title'): _('Вам виповнилося 21 рік?'),
    ('age', 'text'): _('Сайт містить інформацію про тютюнові вироби. Підтвердіть вік, щоб продовжити.'),
    ('age', 'yes'): _('Мені є 21 рік'),
    ('age', 'no'): _('Мені немає 21 року'),
    ('age', 'denied_title'): _('Доступ обмежено'),
    ('age', 'denied_text'): _('Цей сайт призначений лише для повнолітніх відвідувачів 21+.'),
    ('age', 'reset'): _('Повернутися'),
}

PAGE_LABELS: dict[tuple[str, str], str] = {
    ('site', 'header_search_placeholder'): 'Підказка пошуку',
    ('site', 'nav_home'): 'Пункт: Головна',
    ('site', 'nav_catalog'): 'Пункт: Каталог',
    ('site', 'nav_sale'): 'Пункт: Акції',
    ('site', 'nav_faq'): 'Пункт: FAQ',
    ('site', 'nav_about'): 'Пункт: Про нас',
    ('site', 'nav_blog'): 'Пункт: Блог',
    ('site', 'nav_contact'): 'Пункт: Контакти',
    ('site', 'nav_delivery'): 'Пункт: Доставка',
    ('site', 'nav_callback'): 'Кнопка дзвінка',
    ('blog', 'kicker'): 'Kicker блогу',
    ('blog', 'title'): 'Заголовок блогу',
    ('blog', 'lead'): 'Лід блогу',
    ('blog', 'meta_description'): 'Meta description блогу',
    ('blog', 'read_more'): 'Кнопка «Читати»',
    ('blog', 'back'): 'Кнопка «Усі статті»',
    ('blog', 'related'): 'Заголовок «Читайте також»',
    ('site', 'drawer_shop'): 'Мобільне меню: Покупка',
    ('site', 'drawer_info'): 'Мобільне меню: Інфо',
    ('site', 'footer_tagline'): 'Слоган у футері',
    ('site', 'footer_wordmark'): 'Великий напис (низ)',
    ('site', 'footer_copyright'): 'Copyright (повний рядок)',
    ('site', 'footer_seal'): 'Печатка / емблема',
    ('site', 'footer_col_catalog'): 'Колонка: Каталог',
    ('site', 'footer_col_shop'): 'Колонка: Покупка',
    ('site', 'footer_col_info'): 'Колонка: Інфо',
    ('site', 'footer_link_cigars'): 'Посилання: Сигари',
    ('site', 'footer_link_accessories'): 'Посилання: Аксесуари',
    ('site', 'footer_link_brands'): 'Посилання: Бренди',
    ('site', 'footer_link_calculator'): 'Посилання: Калькулятор',
    ('site', 'footer_link_cart'): 'Посилання: Кошик',
    ('site', 'footer_link_cabinet'): 'Посилання: Кабінет',
    ('site', 'footer_link_privacy'): 'Посилання: Приватність',
    ('about', 'kicker'): 'Мітка',
    ('about', 'title'): 'Заголовок',
    ('about', 'lead'): 'Лід',
    ('about', 'image'): 'Фото сторінки',
    ('about', 'years_num'): 'Цифра «років»',
    ('about', 'years_label'): 'Підпис до цифри',
    ('about', 'era1_year'): 'Ера 1 — рік',
    ('about', 'era1_title'): 'Ера 1 — заголовок',
    ('about', 'era1_text'): 'Ера 1 — текст',
    ('about', 'era2_year'): 'Ера 2 — рік',
    ('about', 'era2_title'): 'Ера 2 — заголовок',
    ('about', 'era2_text'): 'Ера 2 — текст',
    ('about', 'era3_year'): 'Ера 3 — рік',
    ('about', 'era3_title'): 'Ера 3 — заголовок',
    ('about', 'era3_text'): 'Ера 3 — текст',
    ('about', 'era4_year'): 'Ера 4 — рік',
    ('about', 'era4_title'): 'Ера 4 — заголовок',
    ('about', 'era4_text'): 'Ера 4 — текст',
    ('faq', 'title'): 'Заголовок',
    ('faq', 'lead'): 'Лід',
    ('faq', 'bg'): 'Фон FAQ',
    ('contact', 'kicker'): 'Мітка',
    ('contact', 'title'): 'Заголовок',
    ('contact', 'lead'): 'Лід',
    ('contact', 'map_label'): 'Підпис карти',
    ('contact', 'submit'): 'Кнопка «Надіслати»',
    ('contact', 'callback'): 'Кнопка дзвінка',
    ('delivery', 'title'): 'Заголовок',
    ('delivery', 'lead'): 'Лід',
    ('delivery', 'bg'): 'Фон доставки',
    ('delivery', 'h2'): 'Підзаголовок доставки',
    ('delivery', 'pay_h2'): 'Підзаголовок оплати',
    ('delivery', 'pay_intro'): 'Вступ до оплати',
    ('b2b', 'title'): 'Заголовок',
    ('b2b', 'lead'): 'Лід',
    ('b2b', 'submit'): 'Кнопка',
    ('booking', 'title'): 'Заголовок',
    ('booking', 'lead'): 'Лід',
    ('booking', 'submit'): 'Кнопка',
    ('catalog', 'empty'): 'Порожній стан',
    ('cart', 'title'): 'Заголовок',
    ('cart', 'empty'): 'Порожній кошик',
    ('cart', 'empty_cta'): 'Кнопка порожнього кошика',
    ('cart', 'continue'): 'Продовжити покупки',
    ('cart', 'checkout'): 'Оформити замовлення',
    ('cart', 'remove'): 'Видалити',
    ('checkout', 'title'): 'Заголовок',
    ('checkout', 'lead'): 'Лід',
    ('checkout', 'submit'): 'Кнопка підтвердження',
    ('checkout', 'summary'): 'Підсумок',
    ('checkout', 'age'): 'Підтвердження віку',
    ('cabinet', 'title'): 'Заголовок',
    ('cabinet', 'lead'): 'Лід',
    ('cabinet', 'profile'): 'Профіль',
    ('cabinet', 'orders'): 'Замовлення',
    ('cabinet', 'empty'): 'Порожні замовлення',
    ('cabinet', 'quick'): 'Швидкі дії',
    ('age', 'title'): 'Заголовок запиту',
    ('age', 'text'): 'Текст запиту',
    ('age', 'yes'): 'Кнопка «Так»',
    ('age', 'no'): 'Кнопка «Ні»',
    ('age', 'denied_title'): 'Заголовок відмови',
    ('age', 'denied_text'): 'Текст відмови',
    ('age', 'reset'): 'Кнопка повернення',
}

PAGE_TYPES: dict[tuple[str, str], str] = {
    ('about', 'image'): 'image',
    ('faq', 'bg'): 'image',
    ('delivery', 'bg'): 'image',
    ('site', 'footer_seal'): 'image',
}

PAGE_INLINE = {
    'header_search_placeholder', 'nav_home', 'nav_catalog', 'nav_sale', 'nav_faq',
    'nav_about', 'nav_blog', 'nav_contact', 'nav_delivery', 'nav_callback', 'drawer_shop',
    'drawer_info', 'footer_col_catalog', 'footer_col_shop', 'footer_col_info',
    'footer_link_cigars', 'footer_link_accessories', 'footer_link_brands',
    'footer_link_calculator', 'footer_link_cart', 'footer_link_cabinet',
    'footer_link_privacy', 'footer_wordmark', 'footer_copyright', 'kicker', 'title',
    'years_num', 'years_label',
    'era1_year', 'era1_title', 'era2_year', 'era2_title', 'era3_year', 'era3_title',
    'era4_year', 'era4_title', 'map_label', 'submit', 'callback', 'h2',
    'pay_h2', 'empty_cta',
    'continue', 'checkout', 'remove', 'summary', 'yes', 'no', 'reset',
    'profile', 'orders', 'empty', 'quick', 'read_more', 'back', 'related',
}
PAGE_MULTILINE = {
    'footer_tagline', 'lead', 'era1_text', 'era2_text', 'era3_text', 'era4_text',
    'pay_intro', 'text', 'denied_text',
    'meta_description',
}
