from __future__ import annotations

from apps.core.site_content_registry import ContentSection, FieldGroup

CONTENT_SECTIONS: tuple[ContentSection, ...] = (
    ContentSection(
        slug='hero',
        page_slug='home',
        title='Головний банер',
        sidebar_title='Головний банер',
        sidebar_icon='image',
        sidebar_group='home',
        preview_url='/',
        admin_model_name='homeherosettings',
        visibility_key='hero_section_visible',
        collection='hero',
        description='Мітка банера та слайди.',
        blocks=(('home', 'hero_eyebrow'),),
        field_groups=(FieldGroup('Мітка', ('hero_eyebrow',)),),
    ),
    ContentSection(
        slug='brands',
        page_slug='home',
        title='Бренди',
        sidebar_title='Бренди',
        sidebar_icon='storefront',
        sidebar_group='home',
        preview_url='/#home-brands',
        admin_model_name='homebrandssettings',
        visibility_key='brands_section_visible',
        collection='brands',
        description='Картки брендів: окреме фото на кожну.',
        blocks=(),
        field_groups=(),
    ),
    ContentSection(
        slug='catalog',
        page_slug='home',
        title='Каталог на головній',
        sidebar_title='Каталог',
        sidebar_icon='inventory_2',
        sidebar_group='home',
        preview_url='/#home-catalog',
        admin_model_name='homecatalogsettings',
        visibility_key='catalog_section_visible',
        blocks=(('home', 'catalog_title'), ('home', 'catalog_all')),
        field_groups=(FieldGroup('Тексти', ('catalog_title', 'catalog_all')),),
    ),
    ContentSection(
        slug='about',
        page_slug='home',
        title='Історія сигар',
        sidebar_title='Історія сигар',
        sidebar_icon='menu_book',
        sidebar_group='home',
        preview_url='/#home-history',
        admin_model_name='homeaboutsettings',
        visibility_key='about_section_visible',
        collection='history',
        blocks=(('home', 'about_kicker'), ('home', 'about_bg')),
        field_groups=(
            FieldGroup('Секція', ('about_kicker',)),
            FieldGroup('Фон', ('about_bg',)),
        ),
    ),
    ContentSection(
        slug='calculator',
        page_slug='home',
        title='Калькулятор',
        sidebar_title='Калькулятор',
        sidebar_icon='calculate',
        sidebar_group='home',
        preview_url='/#home-calculator',
        admin_model_name='homecalculatorsettings',
        visibility_key='calculator_section_visible',
        blocks=(('home', 'calculator_kicker'), ('home', 'calculator_bg')),
        field_groups=(
            FieldGroup('Мітка', ('calculator_kicker',)),
            FieldGroup('Фон', ('calculator_bg',)),
        ),
    ),
    ContentSection(
        slug='service',
        page_slug='home',
        title='Сервіс',
        sidebar_title='Сервіс',
        sidebar_icon='room_service',
        sidebar_group='home',
        preview_url='/#home-booking',
        admin_model_name='homeservicesettings',
        visibility_key='service_section_visible',
        blocks=(
            ('service', 'booking_title'),
            ('service', 'booking_lead'),
            ('service', 'booking_cta'),
            ('service', 'booking_image'),
            ('service', 'b2b_title'),
            ('service', 'b2b_lead'),
            ('service', 'b2b_cta'),
            ('service', 'b2b_image'),
        ),
        field_groups=(
            FieldGroup('Бронювання', ('booking_title', 'booking_lead', 'booking_cta', 'booking_image')),
            FieldGroup('B2B', ('b2b_title', 'b2b_lead', 'b2b_cta', 'b2b_image')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='about',
        title='Про нас',
        sidebar_title='Сторінка',
        sidebar_icon='info',
        sidebar_group='about',
        preview_url='/about/',
        admin_model_name='aboutpagesettings',
        blocks=(
            ('about', 'kicker'), ('about', 'title'), ('about', 'lead'), ('about', 'image'),
            ('about', 'years_num'), ('about', 'years_label'),
            ('about', 'era1_year'), ('about', 'era1_title'), ('about', 'era1_text'),
            ('about', 'era2_year'), ('about', 'era2_title'), ('about', 'era2_text'),
            ('about', 'era3_year'), ('about', 'era3_title'), ('about', 'era3_text'),
            ('about', 'era4_year'), ('about', 'era4_title'), ('about', 'era4_text'),
        ),
        field_groups=(
            FieldGroup('Шапка сторінки', ('kicker', 'title', 'lead', 'image')),
            FieldGroup('Лічильник', ('years_num', 'years_label')),
            FieldGroup('2019', ('era1_year', 'era1_title', 'era1_text')),
            FieldGroup('2021', ('era2_year', 'era2_title', 'era2_text')),
            FieldGroup('2023', ('era3_year', 'era3_title', 'era3_text')),
            FieldGroup('Сьогодні', ('era4_year', 'era4_title', 'era4_text')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='blog',
        title='Блог — шапка',
        sidebar_title='Шапка',
        sidebar_icon='article',
        sidebar_group='blog',
        preview_url='/blog/',
        admin_model_name='blogpagesettings',
        blocks=(
            ('blog', 'kicker'), ('blog', 'title'), ('blog', 'lead'),
            ('blog', 'meta_description'), ('blog', 'read_more'),
            ('blog', 'back'), ('blog', 'related'),
        ),
        field_groups=(
            FieldGroup('Тексти', ('kicker', 'title', 'lead', 'meta_description')),
            FieldGroup('Кнопки', ('read_more', 'back', 'related')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='faq',
        title='FAQ — шапка',
        sidebar_title='Шапка',
        sidebar_icon='help',
        sidebar_group='faq',
        preview_url='/faq/',
        admin_model_name='faqpagesettings',
        blocks=(('faq', 'title'), ('faq', 'lead'), ('faq', 'bg')),
        field_groups=(
            FieldGroup('Тексти', ('title', 'lead')),
            FieldGroup('Фон', ('bg',)),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='contact',
        title='Контакти',
        sidebar_title='Сторінка',
        sidebar_icon='call',
        sidebar_group='contact',
        preview_url='/service/contact/',
        admin_model_name='contactpagesettings',
        blocks=(
            ('contact', 'kicker'), ('contact', 'title'), ('contact', 'lead'),
            ('contact', 'map_label'), ('contact', 'submit'), ('contact', 'callback'),
        ),
        field_groups=(
            FieldGroup('Тексти', ('kicker', 'title', 'lead', 'map_label')),
            FieldGroup('Кнопки', ('submit', 'callback')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='delivery',
        title='Доставка і оплата',
        sidebar_title='Доставка і оплата',
        sidebar_icon='local_shipping',
        sidebar_group='legal',
        preview_url='/service/delivery/',
        admin_model_name='deliverypagesettings',
        collection='delivery',
        description='Шапка, заголовки секцій і динамічні картки (додати / прибрати / порядок).',
        blocks=(
            ('delivery', 'title'), ('delivery', 'lead'), ('delivery', 'bg'),
            ('delivery', 'h2'),
            ('delivery', 'pay_h2'), ('delivery', 'pay_intro'),
        ),
        field_groups=(
            FieldGroup('Шапка сторінки', ('title', 'lead', 'bg')),
            FieldGroup('Секція доставки', ('h2',)),
            FieldGroup('Секція оплати', ('pay_h2', 'pay_intro')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='b2b',
        title='B2B',
        sidebar_title='Сторінка',
        sidebar_icon='handshake',
        sidebar_group='b2b',
        preview_url='/service/b2b/',
        admin_model_name='b2bpagesettings',
        blocks=(('b2b', 'title'), ('b2b', 'lead'), ('b2b', 'submit')),
        field_groups=(FieldGroup('Тексти', ('title', 'lead', 'submit')),),
    ),
    ContentSection(
        slug='page',
        page_slug='booking',
        title='Бронювання',
        sidebar_title='Сторінка',
        sidebar_icon='event',
        sidebar_group='booking',
        preview_url='/booking/',
        admin_model_name='bookingpagesettings',
        blocks=(('booking', 'title'), ('booking', 'lead'), ('booking', 'submit')),
        field_groups=(FieldGroup('Тексти', ('title', 'lead', 'submit')),),
    ),
    ContentSection(
        slug='page',
        page_slug='catalog',
        title='Каталог',
        sidebar_title='Тексти',
        sidebar_icon='category',
        sidebar_group='catalog',
        preview_url='/catalog/',
        admin_model_name='catalogpagesettings',
        blocks=(('catalog', 'empty'),),
        field_groups=(FieldGroup('Порожній стан', ('empty',)),),
    ),
    ContentSection(
        slug='page',
        page_slug='cart',
        title='Кошик',
        sidebar_title='Сторінка',
        sidebar_icon='shopping_bag',
        sidebar_group='cart',
        preview_url='/cart/',
        admin_model_name='cartpagesettings',
        blocks=(
            ('cart', 'title'), ('cart', 'empty'), ('cart', 'empty_cta'),
            ('cart', 'continue'), ('cart', 'checkout'), ('cart', 'remove'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title',)),
            FieldGroup('Порожній', ('empty', 'empty_cta')),
            FieldGroup('Дії', ('continue', 'checkout', 'remove')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='checkout',
        title='Оформлення',
        sidebar_title='Сторінка',
        sidebar_icon='payments',
        sidebar_group='checkout',
        preview_url='/orders/checkout/',
        admin_model_name='checkoutpagesettings',
        blocks=(
            ('checkout', 'title'), ('checkout', 'lead'), ('checkout', 'submit'),
            ('checkout', 'summary'), ('checkout', 'age'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title', 'lead')),
            FieldGroup('Форма', ('submit', 'summary', 'age')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='cabinet',
        title='Кабінет',
        sidebar_title='Сторінка',
        sidebar_icon='person',
        sidebar_group='cabinet',
        preview_url='/account/cabinet/',
        admin_model_name='cabinetpagesettings',
        blocks=(
            ('cabinet', 'title'), ('cabinet', 'lead'), ('cabinet', 'profile'),
            ('cabinet', 'orders'), ('cabinet', 'empty'), ('cabinet', 'quick'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title', 'lead')),
            FieldGroup('Блоки', ('profile', 'orders', 'empty', 'quick')),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='age',
        title='Вікова перевірка',
        sidebar_title='Тексти',
        sidebar_icon='verified_user',
        sidebar_group='age',
        preview_url='/',
        admin_model_name='agegatesettings',
        blocks=(
            ('age', 'title'), ('age', 'text'), ('age', 'yes'), ('age', 'no'),
            ('age', 'denied_title'), ('age', 'denied_text'), ('age', 'reset'),
        ),
        field_groups=(
            FieldGroup('Запит', ('title', 'text', 'yes', 'no')),
            FieldGroup('Відмова', ('denied_title', 'denied_text', 'reset')),
        ),
    ),
    ContentSection(
        slug='header',
        page_slug='site',
        title='Шапка',
        sidebar_title='Шапка',
        sidebar_icon='web',
        sidebar_group='chrome',
        preview_url='/',
        admin_model_name='siteheadersettings',
        blocks=(
            ('site', 'header_search_placeholder'),
            ('site', 'nav_home'), ('site', 'nav_catalog'), ('site', 'nav_sale'),
            ('site', 'nav_faq'), ('site', 'nav_about'), ('site', 'nav_blog'),
            ('site', 'nav_contact'),
            ('site', 'nav_delivery'), ('site', 'nav_callback'),
            ('site', 'drawer_shop'), ('site', 'drawer_info'),
        ),
        field_groups=(
            FieldGroup('Пошук', ('header_search_placeholder',)),
            FieldGroup('Навігація', (
                'nav_home', 'nav_catalog', 'nav_sale', 'nav_faq',
                'nav_about', 'nav_blog', 'nav_contact', 'nav_delivery', 'nav_callback',
            )),
            FieldGroup('Мобільне меню', ('drawer_shop', 'drawer_info')),
        ),
    ),
    ContentSection(
        slug='footer',
        page_slug='site',
        title='Футер',
        sidebar_title='Футер',
        sidebar_icon='vertical_align_bottom',
        sidebar_group='chrome',
        preview_url='/',
        admin_model_name='sitefootersettings',
        description=(
            'Бренд, контакти, слоган, печатка, великий напис і copyright. '
            'Назва / телефон / email також зберігаються в загальних налаштуваннях сайту.'
        ),
        settings_fields=('site_name', 'phone', 'email'),
        blocks=(
            ('site', 'footer_tagline'),
            ('site', 'footer_seal'),
            ('site', 'footer_wordmark'),
            ('site', 'footer_copyright'),
            ('site', 'footer_col_catalog'), ('site', 'footer_col_shop'), ('site', 'footer_col_info'),
            ('site', 'footer_link_cigars'), ('site', 'footer_link_accessories'),
            ('site', 'footer_link_brands'), ('site', 'footer_link_calculator'),
            ('site', 'footer_link_cart'), ('site', 'footer_link_cabinet'),
            ('site', 'footer_link_privacy'),
        ),
        field_groups=(
            FieldGroup('Слоган і печатка', ('footer_tagline', 'footer_seal')),
            FieldGroup('Низ футера', ('footer_wordmark', 'footer_copyright')),
            FieldGroup('Колонки', ('footer_col_catalog', 'footer_col_shop', 'footer_col_info')),
            FieldGroup('Посилання', (
                'footer_link_cigars', 'footer_link_accessories', 'footer_link_brands',
                'footer_link_calculator', 'footer_link_cart', 'footer_link_cabinet',
                'footer_link_privacy',
            )),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='privacy',
        title='Політика конфіденційності',
        sidebar_title='Політика конфіденційності',
        sidebar_icon='policy',
        sidebar_group='legal',
        preview_url='/legal/privacy/',
        admin_model_name='privacypagesettings',
        description='Заголовок, лід, фон і текст політики.',
        blocks=(
            ('privacy', 'title'), ('privacy', 'lead'), ('privacy', 'bg'), ('privacy', 'body'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title', 'lead', 'bg')),
            FieldGroup('Текст', ('body',)),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='terms',
        title='Умови користування',
        sidebar_title='Умови користування',
        sidebar_icon='gavel',
        sidebar_group='legal',
        preview_url='/legal/terms/',
        admin_model_name='termspagesettings',
        description='Заголовок, лід, фон і текст умов.',
        blocks=(
            ('terms', 'title'), ('terms', 'lead'), ('terms', 'bg'), ('terms', 'body'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title', 'lead', 'bg')),
            FieldGroup('Текст', ('body',)),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='age_policy',
        title='Вікова політика',
        sidebar_title='Вікова політика',
        sidebar_icon='verified_user',
        sidebar_group='legal',
        preview_url='/legal/age/',
        admin_model_name='agepolicypagesettings',
        description='Заголовок, лід, фон і текст вікової політики.',
        blocks=(
            ('age_policy', 'title'), ('age_policy', 'lead'),
            ('age_policy', 'bg'), ('age_policy', 'body'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title', 'lead', 'bg')),
            FieldGroup('Текст', ('body',)),
        ),
    ),
    ContentSection(
        slug='page',
        page_slug='cookies',
        title='Файли cookie',
        sidebar_title='Файли cookie',
        sidebar_icon='cookie',
        sidebar_group='legal',
        preview_url='/legal/cookies/',
        admin_model_name='cookiespagesettings',
        description='Заголовок, лід, фон і текст про cookies.',
        blocks=(
            ('cookies', 'title'), ('cookies', 'lead'), ('cookies', 'bg'), ('cookies', 'body'),
        ),
        field_groups=(
            FieldGroup('Шапка', ('title', 'lead', 'bg')),
            FieldGroup('Текст', ('body',)),
        ),
    ),
)
