# Generated by Django 5.2.16 on 2026-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Формат / вітола'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Формат / вітола'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_zh_hans',
            field=models.CharField(max_length=120, null=True, verbose_name='Формат / вітола'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shape_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shape_uk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shape_zh_hans',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Форма'),
        ),
    ]
