# Generated by Django 5.2.16 on 2026-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_i18n_modeltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
    ]
