# Generated by Django 5.2.16 on 2026-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country_uk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country_zh_hans',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Країна'),
        ),
    ]
