# Generated by Django 5.2.16 on 2026-09-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_country_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(
                blank=True,
                help_text='MP4/WebM. Має пріоритет над URL відео.',
                upload_to='products/video/',
                verbose_name='Відеофайл',
            ),
        ),
    ]
