# Generated by Django 5.2.16 on 2026-09-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='binder',
            field=models.CharField(blank=True, max_length=120, verbose_name='Звʼязка (binder)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='binder_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Звʼязка (binder)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='binder_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Звʼязка (binder)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='binder_zh_hans',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Звʼязка (binder)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler',
            field=models.CharField(blank=True, max_length=120, verbose_name='Начинка (filler)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Начинка (filler)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Начинка (filler)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler_zh_hans',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Начинка (filler)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productline', verbose_name='Лінія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL відео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wrapper',
            field=models.CharField(blank=True, max_length=120, verbose_name='Обгортка (wrapper)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wrapper_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Обгортка (wrapper)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wrapper_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Обгортка (wrapper)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wrapper_zh_hans',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Обгортка (wrapper)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Короткий опис зображення (для доступності та SEO).', max_length=200, null=True, verbose_name='Підпис до фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text_uk',
            field=models.CharField(blank=True, help_text='Короткий опис зображення (для доступності та SEO).', max_length=200, null=True, verbose_name='Підпис до фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text_zh_hans',
            field=models.CharField(blank=True, help_text='Короткий опис зображення (для доступності та SEO).', max_length=200, null=True, verbose_name='Підпис до фото'),
        ),
        migrations.AlterField(
            model_name='productline',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_zh_hans',
            field=models.CharField(max_length=80, null=True, verbose_name='Назва'),
        ),
    ]
